export const categories = [
  "All",
  "Editorial",
  "Residential",
  "Materials",
  "Lighting",
  "Hospitality",
  "Process",
];

export const journalPosts = [
  {
    slug: "silence-in-modern-homes",
    title: "What silence looks like in modern Indian homes",
    category: "Editorial",
    readTime: "6 min read",
    date: "May 2026",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=90&w=1600",
    tall: true,
    excerpt:
      "Luxury today is no longer defined by ornament. The most sophisticated homes are often the quietest.",
    showExcerpt: true,
  },
  {
    slug: "the-language-of-stone",
    title: "The language of stone and why it changes a room",
    category: "Materials",
    readTime: "4 min read",
    date: "April 2026",
    image: "https://images.unsplash.com/photo-1533044309907-0fa3413da946?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tall: false,
    excerpt: "Certain materials do not decorate a space. They anchor it emotionally.",
    showExcerpt: false,
  },
  {
    slug: "light-as-architecture",
    title: "Light is not decoration. It is architecture",
    category: "Lighting",
    readTime: "7 min read",
    date: "March 2026",
    image: "https://images.unsplash.com/photo-1560448205-4d9b3e6bb6db?q=90&w=1600",
    tall: false,
    excerpt:
      "A room transforms completely when light is treated as structure rather than accessory.",
    showExcerpt: true,
  },
  {
    slug: "why-luxury-feels-effortless",
    title: "Why the best interiors never announce themselves",
    category: "Residential",
    readTime: "5 min read",
    date: "February 2026",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=90&w=1600",
    tall: true,
    excerpt: "Sophisticated interiors rarely compete for attention. They slow the mind instead.",
    showExcerpt: false,
  },
  {
    slug: "material-intelligence",
    title: "On choosing materials with intention and gravity",
    category: "Process",
    readTime: "5 min read",
    date: "January 2026",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=90&w=1600",
    tall: false,
    excerpt: "We don't select finishes to impress. We choose them to endure.",
    showExcerpt: false,
  },
  {
    slug: "the-aranya-hotel",
    title: "Aranya Hotel: luxury without apology in Jaipur",
    category: "Hospitality",
    readTime: "8 min read",
    date: "December 2025",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=90&w=1600",
    tall: true,
    excerpt: "A commission that demanded restraint at monumental scale.",
    showExcerpt: true,
  },
];

export const tickerWords = [
  "Editorial",
  "Materials",
  "Lighting",
  "Residential",
  "Process",
  "Hospitality",
  "Craft",
  "Atmosphere",
  "Proportion",
  "Silence",
];